baseURL = "http://example.org/"
languageCode = "en-us"
theme = "all-care-beauty"
title = "All Care Beauty"
[permalinks]
  post = "/:title/"

[params]
  address = "7 Barbara Street Fairfield NSW 2165"
  description = "All Care Beauty"
