baseURL = "http://example.org/"
languageCode = "en-us"
theme = "all-care-beauty"
title = "All Care Beauty"
[permalinks]
  post = "/:title/"

[params]
  address = "7 Barbara Street Fairfield NSW 2165"
  description = "We Provide minor cosmetic surgery and botox treatment, using the latest technologies, all at the heart of Western Sydney in Fairfield."
  phone = "(02) 9723 9000"
  email = "dr@allcarebeauty.com.au"
